CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS ROLES(
    id SMALLSERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    code VARCHAR(4) NOT NULL UNIQUE,
    description VARCHAR(256)
);
CREATE TABLE IF NOT EXISTS USERS(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name VARCHAR(128) NOT NULL,
    last_name VARCHAR(128) NOT NULL,
    username VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    phone_number VARCHAR(16) UNIQUE,
    profile_photo VARCHAR(256),
    role_id SMALLINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_role_user FOREIGN KEY (role_id) REFERENCES ROLES(id) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS GROUPS(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(64),
    code VARCHAR(16) UNIQUE NOT NULL,
    description VARCHAR(256),
    owner_id UUID NOT NULL,
    creator_id UUID,
    CONSTRAINT fk_owner_group FOREIGN KEY (owner_id) REFERENCES USERS(id) ON DELETE RESTRICT,
    CONSTRAINT fk_creator_group FOREIGN KEY (creator_id) REFERENCES USERS(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS PROFILES(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    alias VARCHAR(32),
    user_id UUID NOT NULL,
    group_id UUID NOT NULL,
    CONSTRAINT fk_user_profile FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_profiles FOREIGN KEY (group_id) REFERENCES GROUPS(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS MODULES(
    id SMALLSERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    code VARCHAR(64) NOT NULL UNIQUE,
    description VARCHAR(256),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS GROUP_MODULES(
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    group_id UUID NOT NULL,
    module_id UUID NOT NULL,
    CONSTRAINT fk_group FOREIGN KEY (group_id) REFERENCES GROUPS(id) ON DELETE CASCADE,
    CONSTRAINT fk_module FOREIGN KEY (module_id) REFERENCES MODULES(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS PROFILE_MODULES(
    profile_id UUID NOT NULL,
    group_module_id UUID NOT NULL,
    PRIMARY KEY (profile_id, group_module_id),
    permission_value SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_permission_range CHECK ( permission_value >= 0 AND permission_value <= 7 ),
    CONSTRAINT fk_profile FOREIGN KEY (profile_id) REFERENCES PROFILES(id) ON DELETE CASCADE,
    CONSTRAINT fk_module FOREIGN KEY (group_module_id) REFERENCES GROUP_MODULES(id) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END
$$ LANGUAGE plpgsql;
CREATE TRIGGER on_updated_user BEFORE UPDATE ON USERS
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER on_updated_module BEFORE UPDATE ON MODULES
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();